var c =
[
{ImgUrl :"https://www.personality-database.com/profile_images/1984.png" , Type : "INFP" , Name : '"Peter Parker Spider-Man"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/1983.png" , Type : "ISFJ" , Name : 'Steve Rogers Captain America', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/1982.png" , Type : "ENTP" , Name : 'Tony Stark Iron Man', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2017.png" , Type : "ENTP" , Name : 'Wade Wilson Deadpool', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/121938.png" , Type : "ESTP" , Name : 'Julian Keller Hellion', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/121940.png" , Type : "ISFJ" , Name : 'Sofia Mantega Wind Dancer', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/121941.png" , Type : "ENTP" , Name : 'Noriko Ashida Surge', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/128696.png" , Type : "ESTP" , Name : 'Dog Logan', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/156817.png" , Type : "ENTP" , Name : 'Madcap', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/53971.png" , Type : "ISTJ" , Name : 'Adam Brashear Blue Marvel', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/42715.png" , Type : "INTP" , Name : 'Adam Warlock', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/29404.png" , Type : "INTP" , Name : 'Adrian Toomes Vulture', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/254671.png" , Type : "ENTP" , Name : 'Agatha Harkness', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/172998.png" , Type : "ESTP" , Name : 'Alejandro Montoya "El Águila"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/29405.png" , Type : "ISTP" , Name : 'Aleksei Sytsevich "Rhino"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ESFP" , Name : 'Aleta Ogord "Starhawk"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/304175.png" , Type : "ENFP" , Name : 'Alex Power "Zero G"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/153225.png" , Type : "INTJ" , Name : 'Alex Wilder', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/133563.png" , Type : "ESTP" , Name : 'Alexander Summers "Havok"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/56262.png" , Type : "ENTP" , Name : 'Amadeus Cho', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "INTJ" , Name : 'Amahl Farouk "Shadow King"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENFJ" , Name : 'Amara Juliana Olivians "Magma"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/76500.png" , Type : "ESTP" , Name : 'America Chavez', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/133629.png" , Type : "ENTP" , Name : 'Amora Enchantress', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/104304.png" , Type : "ISFP" , Name : 'Andi Benton', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/273195.png" , Type : "ESTP" , Name : 'Angelo Espinosa "Skin"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/57520.png" , Type : "ENFJ" , Name : 'Anita Blake', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/29413.png" , Type : "INTJ" , Name : 'Anna Maria Marconi', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/16110.png" , Type : "INFP" , Name : 'Anna Marie "Rogue"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/42714.png" , Type : "ESTJ" , Name : 'Annihilus', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/59940.png" , Type : "ISTJ" , Name : 'Anthony Masters "Taskmaster"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENFJ" , Name : 'Anya Corazon "Spider-Girl"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENTP" , Name : 'Arcade', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/89383.png" , Type : "ESTJ" , Name : 'Arkady Gregorivich Rossovich " Omega Red "', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/4307.png" , Type : "ESFJ" , Name : 'Aunt May "May Parker"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ISFP" , Name : 'Axel Cluney "Zeitgeist"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/133555.png" , Type : "ISTP" , Name : 'Azazel', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ISTP" , Name : 'B-Negative', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/128662.png" , Type : "ENFP" , Name : 'Bats', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/23647.png" , Type : "ESFJ" , Name : 'Ben Grimm "The Thing"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/41809.png" , Type : "ISFJ" , Name : 'Ben Parker "Uncle Ben"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/185661.png" , Type : "ENFP" , Name : 'Ben Reilly "Scarlet Spider"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "INTJ" , Name : 'Bennet Du Paris "Exodus"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/42716.png" , Type : "ISTJ" , Name : 'Beta Ray Bill', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/29410.png" , Type : "ESFJ" , Name : 'Betty Brant', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/107790.png" , Type : "ENTP" , Name : 'Beyonder', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/5314.png" , Type : "INFP" , Name : 'Billy Kaplan "Wiccan"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/126397.png" , Type : "ENTJ" , Name : 'Blackagar Boltagon "Black Bolt"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENTJ" , Name : 'Blackheart', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/19187.png" , Type : "ESFP" , Name : 'Bobby Drake "Iceman"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ISTJ" , Name : 'Brian Braddock "Captain Britain"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/3598.png" , Type : "ISTP" , Name : 'Brock Rumlow "Crossbones"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2003.png" , Type : "INTP" , Name : 'Bruce Banner "Hulk"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/126955.png" , Type : "INTP" , Name : 'Bruno Carrelli', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/4046.png" , Type : "ISTP" , Name : 'Bucky Barnes "Winter Soldier"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/122970.png" , Type : "ISTP" , Name : 'Bullseye', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/30583.png" , Type : "ESTP" , Name : 'Cain Marko "Juggernaut"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ISFP" , Name : 'Caliban', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/194873.png" , Type : "ESFJ" , Name : 'Carlos Fraile "Captain Spain"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2012.png" , Type : "INFP" , Name : 'Carol Danvers "Captain Marvel", "Ms. Marvel"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/118345.png" , Type : "INFP" , Name : 'Cassandra "Cassie" Lang "Stature"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/57161.png" , Type : "INTJ" , Name : 'Cassandra Nova', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/290943.png" , Type : "INTP" , Name : 'Cecil', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENFP" , Name : 'Chad Channing "Mutant 2099"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2014.png" , Type : "INFJ" , Name : 'Charles Xavier "Professor X"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/22016.png" , Type : "ISFP" , Name : 'Charlie Cluster-7 "Fantomex"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/153224.png" , Type : "ESTP" , Name : 'Chase Stein', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ESTP" , Name : 'Christopher Summers "Corsair"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/5745.png" , Type : "INFP" , Name : 'Cindy Moon "Silk"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/23650.png" , Type : "ENTP" , Name : 'Cletus Kasady "Carnage"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2006.png" , Type : "ESTP" , Name : 'Clint Barton "Hawkeye"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/133638.png" , Type : "ISTP" , Name : 'Conan the Barbarian (Marvel)', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/298826.png" , Type : "ENFJ" , Name : 'Cressida Avenger X', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/133630.png" , Type : "INFP" , Name : 'Crystalia Amaquelin "Crystal"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/163862.png" , Type : "ISTP" , Name : 'Cullen Bloodstone', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/29407.png" , Type : "INTP" , Name : 'Curt Connors "Lizard"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/125507.png" , Type : "ENTJ" , Name : 'Daimon Hellstrom', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/30741.png" , Type : "ISTP" , Name : 'Daken Akihiro', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/67274.png" , Type : "ISFP" , Name : 'Daniel Rand "Iron Fist"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/182109.png" , Type : "INFP" , Name : 'Danielle Moonstar Mirage', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/262370.png" , Type : "INFP" , Name : 'Dave Lizewski', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/54729.png" , Type : "INFP" , Name : 'David "Legion" Haller', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/118348.png" , Type : "ISTJ" , Name : 'David Alleyne "Prodigy"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/57206.png" , Type : "ISTJ" , Name : 'Death', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/78788.png" , Type : "ENTJ" , Name : 'Doc Samson', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENTP" , Name : 'Doc. Green', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ESTP" , Name : 'Dominikos Ioannis Petrakis "Avalanche"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/38913.png" , Type : "ENFP" , Name : 'Doreen Green "Squirrel Girl"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/40486.png" , Type : "ENTJ" , Name : 'Dormammu', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ISFP" , Name : 'Doug Ramsey (Cypher)', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/117596.png" , Type : "ISTP" , Name : 'Dr. Kevin Trench "Nightwatch"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/23649.png" , Type : "ESTP" , Name : 'Eddie Brock "Venom"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/128001.png" , Type : "ENTJ" , Name : 'Ego the Living Planet', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENFJ" , Name : 'Eimin "Apocalypse Twins"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/94325.png" , Type : "ESTP" , Name : 'Elektra Natchios', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/118346.png" , Type : "ISTJ" , Name : 'Elijah Bradley "Patriot"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/59119.png" , Type : "INTJ" , Name : 'Elizabeth Betsy Braddock "Psylocke"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "INFJ" , Name : 'Elliot Boggs "Magician"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/8597.png" , Type : "ENTJ" , Name : 'Emma Frost', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/3754.png" , Type : "INTJ" , Name : 'En Sabah Nur "Apocalypse"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ISTP" , Name : 'Eric Brooks "Blade"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ESTP" , Name : 'Eric OGrady "Ant-Man"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/3183.png" , Type : "INTJ" , Name : 'Erik Lehnsherr "Magneto"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/189110.png" , Type : "ISTP" , Name : 'Eugene Judd "Puck"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/29406.png" , Type : "ESTP" , Name : 'Felicia Hardy "Black Cat"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/304133.png" , Type : "ESFP" , Name : 'Fernanda Ramirez "Red Locust"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/269108.png" , Type : "ISFJ" , Name : 'Fin Fang Foom', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/29414.png" , Type : "ESTP" , Name : 'Flash Thompson "Agent Venom"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/29397.png" , Type : "ESFP" , Name : 'Flint Marko "Sandman"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/21154.png" , Type : "ISTJ" , Name : 'Frank Castle "The Punisher"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENFP" , Name : 'Franklin Richards "Powerhouse"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/98385.png" , Type : "ESFP" , Name : 'Fred Dukes "The Blob"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENTJ" , Name : 'Gabriel Summers "Vulcan"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/3757.png" , Type : "ENTJ" , Name : 'Galactus', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/9466.png" , Type : "ISTP" , Name : 'Gamora', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ISTP" , Name : 'Gaveedra-Seven "Shatterstar"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ESTJ" , Name : 'Genesis', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ISTJ" , Name : 'Georges Batroc "Batroc the Leaper"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/12183.png" , Type : "ENFP" , Name : 'Gert Yorkes', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ESTJ" , Name : 'Graydon Creed', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/91600.png" , Type : "ISFP" , Name : 'Green Hulk', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ISFP" , Name : 'Greg Willis "Gravity"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/91601.png" , Type : "ESTP" , Name : 'Grey Hulk / Joe Fixit', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/32976.png" , Type : "ESFP" , Name : 'Groo', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/9467.png" , Type : "ISFJ" , Name : 'Groot', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "INFJ" , Name : 'Gwen Stacy', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/28443.png" , Type : "ENFP" , Name : 'Gwen Stacy "Spider-Gwen"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/53104.png" , Type : "ENTP" , Name : 'Gwendolyn Poole Gwenpool', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2955.png" , Type : "INTP" , Name : 'Hank McCoy "Beast"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/16040.png" , Type : "INTP" , Name : 'Hank Pym', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENTP" , Name : 'Hannibal King', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/29409.png" , Type : "ENTP" , Name : 'Harry Osborn', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/189113.png" , Type : "ESFJ" , Name : 'Heather McNeil "Vindicator"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "INTJ" , Name : 'Helmut Zemo "Baron Zemo"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/108037.png" , Type : "ESFP" , Name : 'Hercules Panhellenios', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/29398.png" , Type : "ESTP" , Name : 'Herman Schultz "Shocker"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/125503.png" , Type : "INTJ" , Name : 'High Evolutionary', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/47564.png" , Type : "ISTP" , Name : 'Hope Pym "Red Queen"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/83381.png" , Type : "ENFP" , Name : 'Hope Summers', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/30572.png" , Type : "ESTP" , Name : 'Howard the Duck', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/31636.png" , Type : "ISTJ" , Name : 'Ikaris', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/48471.png" , Type : "ENTP" , Name : 'Illyana Rasputin "Magik"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ISTP" , Name : 'Isca "The Unbeaten"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENFP" , Name : 'Itsy Bitsy', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/29408.png" , Type : "ESTJ" , Name : 'J. Jonah Jameson', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/120242.png" , Type : "ENFP" , Name : 'James "Jamie" Braddock Jr.', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2002.png" , Type : "ISTP" , Name : 'James Howlett "Wolverine"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/189109.png" , Type : "ESTJ" , Name : 'James Hudson "Guardian"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ESFP" , Name : 'James Proudstar "Warpath"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/126392.png" , Type : "ISTJ" , Name : 'James Rhodes "War Machine"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/133643.png" , Type : "ENTP" , Name : 'Jamie Madrox "Multiple Man"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/126959.png" , Type : "ISTJ" , Name : 'Jamir Khan', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/129289.png" , Type : "INTP" , Name : 'Jane Foster', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2009.png" , Type : "ESFJ" , Name : 'Janet van Dyne', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENFJ" , Name : 'Jason Wyngarde "Mastermind"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/128214.png" , Type : "ISFJ" , Name : 'Jay Guthrie Icarus', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/154436.png" , Type : "INFJ" , Name : 'Jean Grey "Marvel Girl"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/7460.png" , Type : "ENFJ" , Name : 'Jean Grey "Phoenix"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/103657.png" , Type : "ISFP" , Name : 'Jean-Paul Beaubier "Northstar"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/281847.png" , Type : "ISTP" , Name : 'Jeanne Foucault "Finesse"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/98382.png" , Type : "ENTP" , Name : 'Jeanne Marie Beaubier "Aurora"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/19711.png" , Type : "ENFJ" , Name : 'Jennifer Walters "She-Hulk"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/118005.png" , Type : "ISFP" , Name : 'Jessica Drew "Spider Woman"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/29411.png" , Type : "ISTP" , Name : 'Jessica Jones', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ISTP" , Name : 'Jimmy Hudson "Wolverine"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/306078.png" , Type : "ENFP" , Name : 'Joaquin Torres "Falcon"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/3752.png" , Type : "ENTJ" , Name : 'Johann Shmidt "Red Skull"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ESTJ" , Name : 'John "U.S. Agent" Walker', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/133558.png" , Type : "ESFP" , Name : 'John Allerdyce "Pyro"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/133635.png" , Type : "ENTJ" , Name : 'John Proudstar "Thunderbird"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2018.png" , Type : "ISTP" , Name : 'Johnny Blaze "Ghost Rider"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/4165.png" , Type : "ESFP" , Name : 'Johnny Storm "Human Torch"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/237091.png" , Type : "INTP" , Name : 'Jono Starsmore Chamber', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/133620.png" , Type : "ENTJ" , Name : 'Joseph "Magneto"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/29415.png" , Type : "ISTJ" , Name : 'Joseph "Robbie" Robertson', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/128222.png" , Type : "ISFP" , Name : 'Joshua Foley Elixir', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/237766.png" , Type : "ESFP" , Name : 'Jubilation Lee "Jubilee"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/36343.png" , Type : "ISTP" , Name : 'Julio "Rictor" Richter', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/84759.png" , Type : "ISFP" , Name : 'Ka-Zar', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ISTP" , Name : 'Kaine Parker "Scarlet Spider II"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2870.png" , Type : "ENFP" , Name : 'Kamala Khan "Ms. Marvel"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/125499.png" , Type : "INTJ" , Name : 'Kang the Conqueror', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/125508.png" , Type : "ENTJ" , Name : 'Karla Sofen "Moonstone"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/116684.png" , Type : "ENFJ" , Name : 'Karolina Dean', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/29267.png" , Type : "ENTP" , Name : 'Kate Bishop Hawkeye', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/128227.png" , Type : "ISTP" , Name : 'Kevin Ford Wither', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/295827.png" , Type : "ISTJ" , Name : 'Khonshu', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/11075.png" , Type : "ENTP" , Name : 'Kid Loki', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/3393.png" , Type : "INFP" , Name : 'Kitty Pryde "Shadowcat"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/7764.png" , Type : "INFP" , Name : 'Kurt Wagner "Nightcrawler"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/9628.png" , Type : "ISTP" , Name : 'Laura Kinney "X-23"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/128221.png" , Type : "ENFP" , Name : 'Laurie Collins Wallflower', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/29412.png" , Type : "ESFJ" , Name : 'Liz Allan', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/23648.png" , Type : "ENTP" , Name : 'Loki', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2517.png" , Type : "ISFP" , Name : 'Longshot', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/29402.png" , Type : "ESTJ" , Name : 'Lonnie Lincoln "Tombstone"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/133565.png" , Type : "INFJ" , Name : 'Lorna Dane "Polaris"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/29417.png" , Type : "ESTP" , Name : 'Luke Cage', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/185566.png" , Type : "INFP" , Name : 'Lunella Lafayette Moon Girl', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/29403.png" , Type : "ISTP" , Name : 'Mac Gargan "Scorpion"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/160697.png" , Type : "INFJ" , Name : 'Madame Web', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ESTP" , Name : 'Madelyne Pryor', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/9465.png" , Type : "INFP" , Name : 'Mantis', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/31122.png" , Type : "ENFJ" , Name : 'Mar-Vell, "Captain Marvel"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2871.png" , Type : "ISTJ" , Name : 'Marc Spector "Moon Knight"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/28447.png" , Type : "ENFP" , Name : 'Mary Jane Watson', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/133628.png" , Type : "ISFP" , Name : 'Mary Walker "Typhoid Mary"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2267.png" , Type : "INTJ" , Name : 'Matt Murdock "Daredevil"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/29396.png" , Type : "ESFP" , Name : 'Maxwell Dillon "Electro"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENFJ" , Name : 'May "Mayday" Parker "Spider-Girl"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENFP" , Name : 'Megan Gwynn "Pixie"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "INTJ" , Name : 'Melissa Gold “Songbird”', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/50637.png" , Type : "ENTP" , Name : 'Mephisto', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/86818.png" , Type : "INTJ" , Name : 'Michael Morbius "Morbius"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/126960.png" , Type : "ISFP" , Name : 'Michaela Mike Miller', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/111871.png" , Type : "INTJ" , Name : 'Miguel OHara "Spider-Man"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/15238.png" , Type : "ISFP" , Name : 'Miles Morales "Spider-Man"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "INTP" , Name : 'Mind stone', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/47229.png" , Type : "ESTJ" , Name : 'Miracleman', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/42713.png" , Type : "ENTJ" , Name : 'MODOK', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/199388.png" , Type : "ISTJ" , Name : 'Moira MacTaggert', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ESFP" , Name : 'Molly Hayes', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/314678.png" , Type : "ISTP" , Name : 'Morlun', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/29401.png" , Type : "ISTP" , Name : 'Morris Bench "Hydro-Man"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/98384.png" , Type : "ISTP" , Name : 'Mortimer Toynbee "Toad"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/23257.png" , Type : "ENTJ" , Name : 'NJadaka "Erik Killmonger"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/126961.png" , Type : "ENFJ" , Name : 'Nakia Bahadir', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/15046.png" , Type : "ISTJ" , Name : 'Namor', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/98380.png" , Type : "INTJ" , Name : 'Narya "Snowbird"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2005.png" , Type : "ISTP" , Name : 'Natasha Romanoff "Black Widow"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/57474.png" , Type : "ESTJ" , Name : 'Nathan Summers "Cable"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ESTP" , Name : 'Nathan Summers "kid cable"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/128802.png" , Type : "INTJ" , Name : 'Nathaniel Essex "Mister Sinister"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/133575.png" , Type : "ENTP" , Name : 'Nathaniel Grey "Nate"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/83386.png" , Type : "ISTP" , Name : 'Neena Thurman "Domino"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/254672.png" , Type : "INTJ" , Name : 'Nicholas Scratch', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/41021.png" , Type : "ESTJ" , Name : 'Nick Fury', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/54466.png" , Type : "ENTJ" , Name : 'Nick Fury Jr.', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/5746.png" , Type : "INFP" , Name : 'Nico Minoru', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/128665.png" , Type : "ISTJ" , Name : 'Niels "Hairball"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/274478.png" , Type : "ENTP" , Name : 'Nightmare', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/3755.png" , Type : "ENTJ" , Name : 'Norman Osborn "Green Goblin"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/14667.png" , Type : "INFJ" , Name : 'Norrin Radd "Silver Surfer"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/42735.png" , Type : "ENTJ" , Name : 'Odin', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/221194.png" , Type : "INTJ" , Name : 'One Above All', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/272631.png" , Type : "ISTJ" , Name : 'One Below All', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/221183.png" , Type : "ENTJ" , Name : 'Ophelia Sarkissian "Viper"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/46774.png" , Type : "ENFJ" , Name : 'Ororo Munroe "Storm"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/3756.png" , Type : "INTJ" , Name : 'Otto Octavius “Doctor Octopus”', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/208699.png" , Type : "INFP" , Name : 'Parker Robbins "The Hood', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/126972.png" , Type : "ENFJ" , Name : 'Patsy Walker Hellcat', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ISTP" , Name : 'Penance', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/292445.png" , Type : "ESTP" , Name : 'Peni Parker', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENFJ" , Name : 'Pete Wisdom', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/205185.png" , Type : "INFJ" , Name : 'Peter Parker "The Spider-Man" Noir', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2013.png" , Type : "ENFP" , Name : 'Peter Quill "Star-Lord"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/209136.png" , Type : "ENFJ" , Name : 'Phoenix Force', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2711.png" , Type : "ESTP" , Name : 'Pietro Maximoff "Quicksilver"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/242330.png" , Type : "ISFJ" , Name : 'Piotr “Peter” Rasputin “Colossus”', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "INFJ" , Name : 'Power stone', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENTP" , Name : 'Professor Hulk', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/29399.png" , Type : "INTJ" , Name : 'Quentin Beck "Mysterio"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/259520.png" , Type : "INTJ" , Name : 'Quentin Quire "Kid Omega"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/83382.png" , Type : "ISTP" , Name : 'Rachel Summers', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/19096.png" , Type : "INFJ" , Name : 'Rahne Sinclair "Wolfsbane"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/133549.png" , Type : "ISTP" , Name : 'Raven Darkhölme "Mystique"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENTP" , Name : 'Reality stone', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/94953.png" , Type : "ESTJ" , Name : 'Red Hulk', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2016.png" , Type : "INTP" , Name : 'Reed Richards "Mister Fantastic"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2954.png" , Type : "ESTP" , Name : 'Remy LeBeau "Gambit"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ISFP" , Name : 'Richard Rider "Nova"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/133639.png" , Type : "ESFP" , Name : 'Rick Jones', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/74178.png" , Type : "INTJ" , Name : 'Riri Williams "Ironheart"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/50156.png" , Type : "ISFJ" , Name : 'Robert Reynolds "Sentry"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/133616.png" , Type : "ESFP" , Name : 'Roberto da Costa "Sunspot"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/26235.png" , Type : "ESTP" , Name : 'Rocket Raccoon', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ISFP" , Name : 'Rusty Collins "Firefist"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENFJ" , Name : 'Safespace', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/273196.png" , Type : "INTP" , Name : 'Sally Floyd', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/208687.png" , Type : "ENFJ" , Name : 'Sam Alexander "Nova"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "INFP" , Name : 'Sam Guthrie "Cannonball"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2643.png" , Type : "ISFP" , Name : 'Sam Wilson "Falcon"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/12548.png" , Type : "INTJ" , Name : 'Samuel Sterns "The Leader"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/276565.png" , Type : "ENFJ" , Name : 'Santa Claus', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/128224.png" , Type : "ESTP" , Name : 'Santo Vacarro “Rockslide”', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/293209.png" , Type : "INFJ" , Name : 'Sarah "Terrible Eye"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENTJ" , Name : 'Satana Hellstorm', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "INTP" , Name : 'Sauron', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2007.png" , Type : "ENTP" , Name : 'Scott Lang "Ant-Man"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2015.png" , Type : "ISTJ" , Name : 'Scott Summers "Cyclops"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ESFP" , Name : 'ScreenTime', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENFJ" , Name : 'Selah Burke "Sun Girl"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ESFJ" , Name : 'Selene Gallio "Black Queen"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/181304.png" , Type : "INFJ" , Name : 'Seol Hee “Luna Snow”', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/29400.png" , Type : "ESTP" , Name : 'Sergei Kravinoff "Kraven The Hunter"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/31637.png" , Type : "ESTJ" , Name : 'Sersi', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/181307.png" , Type : "ISTP" , Name : 'Shadow Shell', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/185603.png" , Type : "ENTJ" , Name : 'Shiklah', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/40487.png" , Type : "ENTJ" , Name : 'Shuma-Gorath', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/54805.png" , Type : "ENTP" , Name : 'Simon Williams "Wonder Man"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENTP" , Name : 'Solem', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/191963.png" , Type : "ISTJ" , Name : 'Space stone', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/122792.png" , Type : "ESFP" , Name : 'Speedball', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ISTJ" , Name : 'Stakar Ogord "Starhawk"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2011.png" , Type : "INTJ" , Name : 'Stephen Strange "Doctor Strange"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "INTJ" , Name : 'stone', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENFJ" , Name : 'Sun Bird', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENFJ" , Name : 'Superior (Bastards of Evil)', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/215004.png" , Type : "INTJ" , Name : 'Superior Spiderman', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/179377.png" , Type : "ENTJ" , Name : 'Surtur', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/38540.png" , Type : "ENFJ" , Name : 'Susan Storm "Invisible Woman"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2010.png" , Type : "INTJ" , Name : 'TChalla "Black Panther"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/304386.png" , Type : "ENFJ" , Name : 'TANDY BOWEN "DAGGER"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/268512.png" , Type : "INFJ" , Name : 'Ted Sallis "Man-Thing"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/128016.png" , Type : "ENFJ" , Name : 'Teddy Altman Hulkling', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/303099.png" , Type : "INFJ" , Name : 'Terrance Ward "Trauma"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/41967.png" , Type : "ESTJ" , Name : 'Thaddeus "Thunderbolt" Ross', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2601.png" , Type : "ENTJ" , Name : 'Thanos', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/128688.png" , Type : "INTJ" , Name : 'The Living Tribunal', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/84226.png" , Type : "INTP" , Name : 'The Maker/ Ultimate Reed Richards', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ISFP" , Name : 'Theresa Maeve Rourke Cassidy "Siryn"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/118347.png" , Type : "ESTP" , Name : 'Thomas Shepherd "Speed"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2004.png" , Type : "ESTP" , Name : 'Thor Odinson', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "INTJ" , Name : 'Time stone', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ENFP" , Name : 'Trevor Hawkins "Eye-Boy"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/172993.png" , Type : "INFJ" , Name : 'Tyrone Johnson "Cloak"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/66575.png" , Type : "INTP" , Name : 'Uatu "The Watcher"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/127643.png" , Type : "INTP" , Name : 'Ultimate Spider-Man (Peter Parker)', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ESFP" , Name : 'Ultimate Thor', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/40485.png" , Type : "ENTJ" , Name : 'Ultron', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "INFJ" , Name : 'Uriel "Apocalypse Twins"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/70878.png" , Type : "INTJ" , Name : 'Valeria Richards “Brainstorm”', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/133553.png" , Type : "ESTP" , Name : 'Victor Creed "Sabretooth"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2602.png" , Type : "INTJ" , Name : 'Victor von Doom "Doctor Doom"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/2878.png" , Type : "INFJ" , Name : 'Vision', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/104297.png" , Type : "ISFP" , Name : 'Viv Vision', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/8598.png" , Type : "INFP" , Name : 'Wanda Maximoff "Scarlet Witch"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ESTP" , Name : 'War Tiger', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "INFJ" , Name : 'Warlock', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/19188.png" , Type : "ESFJ" , Name : 'Warren Worthington III "Angel/Archangel"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ESTP" , Name : 'Wendell Vaughn "Quasar"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/181536.png" , Type : "ESTJ" , Name : 'William Stryker', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/3753.png" , Type : "ESTJ" , Name : 'Wilson Fisk "Kingpin"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/images/profile_transparent.png" , Type : "ISFJ" , Name : 'Xorn', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/77120.png" , Type : "INTJ" , Name : 'Yelena Belova', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/74298.png" , Type : "ENTP" , Name : 'Zebediah Killgrave "Purple Man"', Category : "Marvel Comics" },
{ImgUrl :"https://www.personality-database.com/profile_images/126962.png" , Type : "ENFJ" , Name : 'Zoe Zimmer', Category : "Marvel Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/1985.png" , Type : "INTJ" , Name : "Bruce Wayne Batman" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/1986.png" , Type : "ISFJ" , Name : "Kal-El Superman" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/1987.png" , Type : "ENFJ" , Name : "Diana Prince Wonder Woman" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/11322.png" , Type : "INFP" , Name : "Ace" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/2026.png" , Type : "ENTP" , Name : "Adam Strange" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/259855.png" , Type : "ESTJ" , Name : "Adeline Kane" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/7780.png" , Type : "INTJ" , Name : "Adrian Veidt Ozymandias" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/299591.png" , Type : "ENTJ" , Name : "Ahn Kwang-Jo Dragonson" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/43180.png" , Type : "ISTJ" , Name : "Alan Scott Green Lantern" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/37538.png" , Type : "INFJ" , Name : "Alec Holland Swamp Thing" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/2876.png" , Type : "ISFJ" , Name : "Alfred Pennyworth" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/133458.png" , Type : "INTP" , Name : "Alice Kane" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/260507.png" , Type : "ISFP" , Name : "Alinta Bolt" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/208761.png" , Type : "ESTP" , Name : "Alix Harrower Bulleteer" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/74138.png" , Type : "INFJ" , Name : "All Star Superman" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/122344.png" , Type : "ENTJ" , Name : "Alpheus" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/85020.png" , Type : "ENTJ" , Name : "Amanda Waller" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/208747.png" , Type : "ISTP" , Name : "Amy Allen Bombshell" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/162176.png" , Type : "INFJ" , Name : "Amy Winston Amethyst" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/285333.png" , Type : "ISTP" , Name : "Andrea Beaumont The Phantasm" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/288306.png" , Type : "ESTJ" , Name : "Andrej Trojan" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/288303.png" , Type : "ENFJ" , Name : "Andrew Pulaski Apollo" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/260506.png" , Type : "ENFP" , Name : "Andrina Curry Aquawoman" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/276099.png" , Type : "ISFJ" , Name : "Anissa Pierce Thunder" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/162207.png" , Type : "ESFP" , Name : "Anita Fite Empress" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/46772.png" , Type : "ENTJ" , Name : "Anti Monitor" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/85008.png" , Type : "INFP" , Name : "Aquagirl" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/263702.png" , Type : "ESTJ" , Name : "Ares" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/28601.png" , Type : "ISTP" , Name : "Artemis Crock Tigress" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/178625.png" , Type : "ESTJ" , Name : "Artemis Grace" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/images/profile_transparent.png" , Type : "INTJ" , Name : "Arthur Brown The Cluemaster" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/1993.png" , Type : "ENTJ" , Name : "Arthur Curry Aquaman" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/46735.png" , Type : "ESTJ" , Name : "Atrocitus" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/108414.png" , Type : "ENTJ" , Name : "August Heart Godspeed" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/108359.png" , Type : "INTJ" , Name : "Augustus Freeman Icon" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/108400.png" , Type : "ESTP" , Name : "Avery Ho The Flash" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/297490.png" , Type : "ENFP" , Name : "Axel Walker The Trickster" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/100179.png" , Type : "ENFJ" , Name : "Ayla Ranzz Lightning Lass" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/3555.png" , Type : "ISTP" , Name : "Bane" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/208707.png" , Type : "ISTJ" , Name : "Bao Pham Clownhunter" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/83383.png" , Type : "ESTP" , Name : "Barbara Ann Minerva Cheetah" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/2024.png" , Type : "INFJ" , Name : "Barbara Gordon Batgirl" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/64656.png" , Type : "ESFJ" , Name : "Barda Free Big Barda" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/1991.png" , Type : "INFP" , Name : "Barry Allen The Flash" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/16674.png" , Type : "ENFP" , Name : "Bart Allen Impulse" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/124475.png" , Type : "ISFP" , Name : "Basil Karlo Clayface" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/159784.png" , Type : "ESFP" , Name : "Batman of Zur-En-Arrh" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/280147.png" , Type : "ENFJ" , Name : "Beatriz da Costa Fire" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/188515.png" , Type : "ENFJ" , Name : "Bernhard Baker Animal Man" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/2020.png" , Type : "ESFP" , Name : "Billy Batson Shazam" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/108386.png" , Type : "ESFP" , Name : "Billy Wu Roundhouse" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/46737.png" , Type : "ISFP" , Name : "Bizarro" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/299712.png" , Type : "ISTJ" , Name : "Black Flash" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/227032.png" , Type : "INTJ" , Name : "Black Lantern Corps (Death)" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/227025.png" , Type : "INFJ" , Name : "Blue Lantern Corps (Emotion: Hope)" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/237280.png" , Type : "INTP" , Name : "Bobo T. Chimpanzee Detective Chimp" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/46739.png" , Type : "ENFP" , Name : "Boston Brand Deadman" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/292383.png" , Type : "INTJ" , Name : "Brick Pettirosso Brick" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/299593.png" , Type : "ENTP" , Name : "Bruce Wayne Robin King" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/66559.png" , Type : "ENTJ" , Name : "Bryce Wayne The Drowned" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/86434.png" , Type : "ISTJ" , Name : "Caitlin Snow Killer Frost" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/253047.png" , Type : "ENFJ" , Name : "Calvin Ellis Superman (Earth-23)" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/46733.png" , Type : "ENFJ" , Name : "Carol Ferris Star Sapphire" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/142059.png" , Type : "ENFP" , Name : "Caroline Keene Carrie Kelley" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/4472.png" , Type : "ESTJ" , Name : "Carter Hall Hawkman" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/42095.png" , Type : "ISFP" , Name : "Cassandra Cain Orphan" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/108412.png" , Type : "ESFP" , Name : "Cassie Sandsmark Wonder Girl" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/100161.png" , Type : "ENTJ" , Name : "Cat Grant" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/188664.png" , Type : "ESFP" , Name : "Charles Brown Kite-Man" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/178822.png" , Type : "ENFJ" , Name : "Christopher Smith Peacemaker" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/276094.png" , Type : "ESFP" , Name : "Clifford Steele Robotman" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/162156.png" , Type : "ISTP" , Name : "Cole Cash Grifter" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/264624.png" , Type : "ENFP" , Name : "Condiment King" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/276007.png" , Type : "INTJ" , Name : "Connor Hawke Green Arrow" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/280283.png" , Type : "ESTJ" , Name : "Copper" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/276070.png" , Type : "ENFJ" , Name : "Courtney Whitmore Stargirl" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/86431.png" , Type : "ISTJ" , Name : "Crystal Frost Killer Frost" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/2873.png" , Type : "ENTJ" , Name : "Damian Wayne Robin" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/2025.png" , Type : "ISFJ" , Name : "Daniel Dreiberg Nite Owl" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/72618.png" , Type : "ENTJ" , Name : "Dark Knight Returns Batman" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/72316.png" , Type : "ENTP" , Name : "Dark Knight Returns Joker" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/72712.png" , Type : "ENFJ" , Name : "Dark Knight Returns Superman" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/3745.png" , Type : "ENTJ" , Name : "Darkseid" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/72371.png" , Type : "ESFP" , Name : "Darla Dudley" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/3748.png" , Type : "INTJ" , Name : "David Kane Black Manta" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/285337.png" , Type : "ENFP" , Name : "Dawn Granger Dove" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/71371.png" , Type : "ENFJ" , Name : "Deacon Blackfire" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/34470.png" , Type : "ENFP" , Name : "Death (The Sandman)" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/34472.png" , Type : "ENFP" , Name : "Delirium (The Sandman)" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/72354.png" , Type : "INFP" , Name : "Derek James Sideways" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/34471.png" , Type : "ENTP" , Name : "Desire (The Sandman)" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/58315.png" , Type : "ISFP" , Name : "Despair (The Sandman)" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/56949.png" , Type : "ISTJ" , Name : "Destiny (The Sandman)" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/56950.png" , Type : "ISTP" , Name : "Destruction (The Sandman)" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/269538.png" , Type : "ISTP" , Name : "Devon Death Masque" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/285392.png" , Type : "ISFP" , Name : "Dexter Dex-Starr" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/1997.png" , Type : "ENFJ" , Name : "Dick Grayson Nightwing" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/297487.png" , Type : "ISTP" , Name : "Digger Harkness Captain Boomerang" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/2021.png" , Type : "ESFJ" , Name : "Dinah Drake Black Canary" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/108384.png" , Type : "INFJ" , Name : "Djinn" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/285383.png" , Type : "ENFJ" , Name : "Donna Fury" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/46724.png" , Type : "ESTJ" , Name : "Donna Troy" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/3751.png" , Type : "ISTP" , Name : "Doomsday" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/57521.png" , Type : "INTP" , Name : "Dr Simon Hurt" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/100180.png" , Type : "ENTJ" , Name : "Dr. David Connor Eradicator" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/34469.png" , Type : "INTJ" , Name : "Dream (The Sandman)" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/78660.png" , Type : "ESTJ" , Name : "Dru-Zod General Zod" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/108372.png" , Type : "INFJ" , Name : "Duke Thomas The Signal" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/212521.png" , Type : "INFP" , Name : "Eddie Bloomberg Red Devil" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/7779.png" , Type : "ESTP" , Name : "Edward Blake The Comedian" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/4800.png" , Type : "INTP" , Name : "Edward Nygma The Riddler" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/100772.png" , Type : "INTJ" , Name : "Emiko Queen Red Arrow" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/3747.png" , Type : "INTJ" , Name : "Eobard Thawne Reverse-Flash" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/72372.png" , Type : "INTP" , Name : "Eugene Choi" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/129249.png" , Type : "INTP" , Name : "First Victim" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/260533.png" , Type : "ENTP" , Name : "Flatline" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/222871.png" , Type : "ESFP" , Name : "Floyd Belkin Arm-Fall-Off-Boy" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/3553.png" , Type : "ISTP" , Name : "Floyd Lawton Deadshot" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/72368.png" , Type : "ENTP" , Name : "Freddy Freeman" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/151625.png" , Type : "INFJ" , Name : "Ganthet" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/64027.png" , Type : "ESFP" , Name : "Garfield Logan Beast Boy" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/253045.png" , Type : "ESTJ" , Name : "Garth Tempest" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/100176.png" , Type : "ESTP" , Name : "Garth Ranzz Lightning Lad / LiveWire" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/221780.png" , Type : "ENTP" , Name : "Ghost-maker" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/205837.png" , Type : "ISTP" , Name : "Golden Age Batman" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/205839.png" , Type : "ENFJ" , Name : "Golden Age Superman" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/5743.png" , Type : "INTJ" , Name : "Gorilla Grodd" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/181832.png" , Type : "ENTJ" , Name : "Grant Wilson Ravager" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/227023.png" , Type : "ENFJ" , Name : "Green Lantern Corps (Emotion: Will)" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/162205.png" , Type : "INFJ" , Name : "Greta Hayes Secret" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/37077.png" , Type : "ESTP" , Name : "Guy Gardner Red Lantern" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/1992.png" , Type : "ESFP" , Name : "Hal Jordan Green Lantern" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/285336.png" , Type : "ISTP" , Name : "Hank Hall Hawk" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/3554.png" , Type : "ENFP" , Name : "Harleen Quinzel Harley Quinn" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/304691.png" , Type : "ISFJ" , Name : "Harold Jordan Power Ring" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/118344.png" , Type : "ESFJ" , Name : "Harper Row Bluebird" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/297491.png" , Type : "INFP" , Name : "Hartley Rathaway Pied Piper" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/29419.png" , Type : "ESTJ" , Name : "Harvey Dent Two-Face" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/151630.png" , Type : "INTJ" , Name : "Hector Hammond" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/12069.png" , Type : "ISTP" , Name : "Helena Bertinelli Huntress" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/132232.png" , Type : "ENTJ" , Name : "Helena Wayne" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/46723.png" , Type : "ISTJ" , Name : "Heretic" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/280247.png" , Type : "ENTJ" , Name : "Hernan Guerra Superman" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/67773.png" , Type : "ENFJ" , Name : "HighFather" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/46722.png" , Type : "ISTP" , Name : "Hooded Justice" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/127346.png" , Type : "INTJ" , Name : "Hugo Strange" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/151879.png" , Type : "ENTJ" , Name : "Hunter Zolomon Zoom" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/100175.png" , Type : "ESFJ" , Name : "Imra Ardeen Saturn Girl" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/227031.png" , Type : "INFJ" , Name : "Indigo Tribe (Emotion: Compassion)" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/280207.png" , Type : "ENTP" , Name : "Inque" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/100169.png" , Type : "ISTJ" , Name : "Inspector William Henderson" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/151628.png" , Type : "ISTP" , Name : "Invisible Destroyer" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/222867.png" , Type : "ENTP" , Name : "Irwin Schwab Ambush Bug" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/1995.png" , Type : "INFJ" , Name : "J'onn J'onnz Martian Manhunter" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/images/profile_transparent.png" , Type : "INTJ" , Name : "Jack Napier  White Knight " , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/212519.png" , Type : "ENFP" , Name : "Jack Ryder Creeper" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/72356.png" , Type : "ISTJ" , Name : "Jackson Hyde Aqualad" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/118328.png" , Type : "ENTJ" , Name : "Jacob Kane" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/276086.png" , Type : "ESTP" , Name : "Jade Nguyen Cheshire" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/276024.png" , Type : "ISFP" , Name : "Jai West" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/127067.png" , Type : "ENFP" , Name : "Jaime Reyes Blue Beetle" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/31466.png" , Type : "ISTJ" , Name : "James Gordon" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/297493.png" , Type : "ENTP" , Name : "James Jesse The Trickster" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/285334.png" , Type : "ENTP" , Name : "Jarro" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/46731.png" , Type : "ESTP" , Name : "Jason Blood Etrigan the Demon" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/2874.png" , Type : "ISTP" , Name : "Jason Todd Red Hood" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/31242.png" , Type : "ISFJ" , Name : "Jay Garrick The Flash" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/36902.png" , Type : "ISTJ" , Name : "Jean-Paul Valley Azrael" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/108374.png" , Type : "ENFJ" , Name : "Jefferson Pierce Black Lightning" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/299715.png" , Type : "ESFP" , Name : "Jenni Ognats XS" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/260495.png" , Type : "ENFJ" , Name : "Jess Chambers The Flash" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/276027.png" , Type : "ESFP" , Name : "Jesse Chambers Jesse Quick" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/73939.png" , Type : "ENFP" , Name : "Jessica Cruz Green Lantern" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/170066.png" , Type : "ENFP" , Name : "Jesus Chris Christ" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/46732.png" , Type : "ISFP" , Name : "Jimmy Olsen" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/162182.png" , Type : "ESFP" , Name : "Jinny Hex" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/7763.png" , Type : "ENTP" , Name : "John Constantine" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/37076.png" , Type : "ISTJ" , Name : "John Stewart Green Lantern" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/289385.png" , Type : "ENFP" , Name : "Johnny Thunder" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/58909.png" , Type : "ESFJ" , Name : "Jon Kent Superboy" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/2029.png" , Type : "INTP" , Name : "Jon Osterman Dr. Manhattan" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/174102.png" , Type : "ISTP" , Name : "Jonah Hex" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/36893.png" , Type : "INTP" , Name : "Jonathan Crane Scarecrow" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/162211.png" , Type : "INFP" , Name : "Joseph Wilson Jericho" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/23091.png" , Type : "ISTJ" , Name : "Judas Iscariot Phantom Stranger" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/101946.png" , Type : "INTJ" , Name : "Julian Day Calendar Man" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/108375.png" , Type : "ESFP" , Name : "Kal-El Superboy-Prime" , Category : "DC Comics" },
{ImgUrl : "https://www.personality-database.com/profile_images/2877.png" , Type : "ESFJ" , Name : "Kara Zor-El Supergirl" , Category : "DC Comics" }
];

module.exports = c;